# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.CharField(max_length=20)),
                ('clue_text', models.CharField(max_length=100)),
                ('clue_answer', models.CharField(max_length=20)),
                ('image_copyright', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=20)),
                ('user_location', models.CharField(max_length=200)),
                ('user_score', models.IntegerField()),
                ('user_name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='date of game')),
            ],
        ),
    ]
