# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageReveal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='clue_answer_length',
            field=models.CharField(default='Default', max_length=15),
            preserve_default=False,
        ),
    ]
