# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageReveal', '0002_clue_clue_answer_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='image_copyright',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
